version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/deployer"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/laravel"
    schedule:
      interval: "daily"